#!/bin/bash

source ./utils

shouldLoopback=$1

currSong=""
wasPlaying=false

source ./tf2ConfigFileParser

avplayProcId="nope"
sed -i -e "s/a.*/a$avplayProcId/" /tmp/PikaDJ/resourceIDs.tmp

getFirstSong() {
	echo "playlist" | nc -w 5 127.0.0.1 $vlcPort | sed -e 's/[\r\n]//g' | sed -n -e 's/^|   [0-9]* - \(.*\) ([0-9:]*).*/\1/p' | head -1 | sed -e 's/\.[a-zA-Z0-9]\{2,4\}$//'
}

getLastSong() {
	echo "playlist" | nc -w 5 127.0.0.1 $vlcPort | sed -e 's/[\r\n]//g' | sed -n -e 's/^|   [0-9]* - \(.*\) ([0-9:]*).*/\1/p' | tail -1 | sed -e 's/\.[a-zA-Z0-9]\{2,4\}$//'
}

noSong() {
	wasPlaying=false
	if [[ $currSong == "$(getLastSong)" ]]; then
		echo "clear" | nc -w 5 127.0.0.1 $vlcPort >/dev/null 2>/dev/null
		rm -f ~/Music/youtubeRequests/fixedName/* >/dev/null 2>/dev/null
		currSong=""
	fi
	if [[ $shouldLoopback != "0" ]]; then
		echo "Reset mic source due to song stop!" >/dev/null 2>/dev/null
		kill -9 $avplayProcId >/dev/null 2>/dev/null
		wait $avplayProcId >/dev/null 2>/dev/null
		echo "micspamEnable" >> stdin
		appIndex=0
		while [[ $appIndex != "null" ]]; do
			while read sourceLine; do
				case $sourceLine in
					index:\ *) appIndex=$(echo "$sourceLine" | sed -e 's/.*index: \(.*\)/\1/') ;;
					application.name\ =\ *) if [[ $(echo "$sourceLine" | sed -e 's/.*application\.name = \"\(.*\)\"/\1/') == "Steam" ]]; then echo "Found it at $appIndex"; pacmd move-source-output $appIndex $(pacmd list-sources | grep -i \* | sed -e 's/.*index: \(.*\)/\1/'); appIndex="null"; break; fi ;;
				esac
			done < <(pacmd list-source-outputs) >/dev/null 2>/dev/null
		done
	fi
	echo "micspamDisable" >> stdin
}

while true
do
	watch -g -n 0.25 'echo "status" | nc -w 5 127.0.0.1 '$vlcPort' | sed -n -e "s/> ( new input: \(.*\) ).*/\1/p"' >/dev/null 2>/dev/null
	source ./tf2ConfigFileParser
	> /tmp/PikaDJ/voteSkip.tmp
	songInfo="$(getSongInfo)"
	if [[ $songInfo != "" ]]; then
		if [[ $songInfo == "$(getFirstSong)" ]] && [[ $currSong == "$(getLastSong)" ]]; then
			echo "micspamDisable" >> stdin
			echo "clear" | nc -w 5 127.0.0.1 $vlcPort >/dev/null 2>/dev/null
			rm -f ~/Music/youtubeRequests/fixedName/*  >/dev/null 2>/dev/null
			noSong
			continue
		fi
		if $wasPlaying && ! $autoplay; then
			echo "stop" | nc -w 5 127.0.0.1 $vlcPort >/dev/null 2>/dev/null
			noSong
			continue
		fi
		wasPlaying=true
		currSong=$songInfo
		echo "micspamDisable" >> stdin
		kill -9 $avplayProcId >/dev/null 2>/dev/null
		wait $avplayProcId >/dev/null 2>/dev/null
		songFile=$(echo "status" | nc -w 5 127.0.0.1 $vlcPort | sed -n -e 's/> ( new input: file:\/\/\(.*\) ).*/\1/p')
		if ! [[ $songFile =~ ^.*\.wav$ ]]; then
			avconv -y -i "$songFile" /tmp/PikaDJ/soxin.wav >/dev/null 2>/dev/null
			songFile="/tmp/PikaDJ/soxin.wav"
		fi
		if [[ $shouldLoopback == "0" ]]; then
			sox "$songFile" -e signed-integer -b 16 --endian little -c 1 ../voice_input.wav gain -B -n $gain0 rate 11025 sinc $sincRange0 bass $bassReduction0 gain -B -n $gain0 pad 1.5 1.5 silence 1 0.1 0.01% reverse silence 1 0.1 0.01% reverse; echo "micspamEnable" >> stdin &
		else
			sox "$songFile" -e signed-integer -b 16 --endian little -c 1 ../voice_input.wav gain -B -n $gain1 rate 11025 sinc $sincRange1 bass $bassReduction1 gain -B -n $gain1 pad 1.5 1.5 silence 1 0.1 0.01% reverse silence 1 0.1 0.01% reverse
			avplay -i ../voice_input.wav -nodisp >/dev/null 2>/dev/null &
			avplayProcId=$!
			sed -i -e "s/a.*/a$avplayProcId/" /tmp/PikaDJ/resourceIDs.tmp
			echo "micspamEnable" >> stdin
			appIndex=0
			while [[ $appIndex != "null" ]]; do
				while read line; do
					case $line in
						index:\ *) appIndex=$(echo "$line" | sed -e 's/.*index: \(.*\)/\1/') ;;
						application.name\ =\ *) if [[ $(echo "$line" | sed -e 's/.*application\.name = \"\(.*\)\"/\1/') == "Steam" ]]; then echo "Found it at $appIndex"; pacmd move-source-output $appIndex "null_TF2Micspam.monitor"; appIndex="null"; break; fi ;;
					esac
				done < <(pacmd list-source-outputs) >/dev/null 2>/dev/null
			done
			appIndex=0
			while [[ $appIndex != "null" ]]; do
				while read line; do
					case $line in
						index:\ *) appIndex=$(echo "$line" | sed -e 's/.*index: \(.*\)/\1/') ;;
						application.process.id\ =\ *) if [[ $(echo "$line" | sed -e 's/.*application\.process\.id = \"\(.*\)\"/\1/') == "$avplayProcId" ]]; then echo "Found it at $appIndex"; pacmd move-sink-input $appIndex "null_TF2Micspam"; appIndex="null"; break; fi ;;
					esac
				done < <(pacmd list-sink-inputs) >/dev/null 2>/dev/null
			done
		fi
		echo "play" | nc -w 5 127.0.0.1 $vlcPort >/dev/null 2>/dev/null
		echo "seek 0" | nc -w 5 127.0.0.1 $vlcPort >/dev/null 2>/dev/null
		sleep 1.5
		#songInfo="\"$songTitle\"$songArtist"
		#echo "say [PikaDJ] Now Playing: $songInfo" >> stdin
		saySongInfo
		> /tmp/PikaDJ/voteSkip.tmp
	else
		noSong
	fi
done
exit 0
